# Document Processing Configuration
indexing:
  input_directory: "data/input"
  output_directory: "data/output"
  chunk_size: 1000              # tokens per chunk
  chunk_overlap: 200            # overlap between chunks
  batch_size: 10                # files to process at once
  enable_ocr: true              # enable OCR for images
  supported_formats:
    - pdf
    - docx
    - pptx
    - xlsx
    - txt
    - md

# Embedding Configuration
embeddings:
  model_name: "nomic-ai/nomic-embed-text-v1"
  dimension: 768
  device: "cpu"                 # cpu, cuda, mps (for M1 Macs)
  batch_size: 32
  normalize: true

# Retrieval Configuration
retrieval:
  fusion_method: "rrf"          # reciprocal rank fusion
  top_k_per_source: 20          # results from each search engine
  final_top_k: 10               # final results after fusion
  min_similarity_threshold: 0.0
  rrf_k: 60                     # RRF parameter
  concurrent_search: true       # run searches in parallel
  search_timeout: 30.0          # timeout in seconds

# Qdrant Configuration
qdrant:
  url: "http://localhost:6333"
  collection: "optimaize_documents"
  vector_size: 768
  distance: "Cosine"
  batch_size: 100

# Elasticsearch Configuration  
elasticsearch:
  url: "http://localhost:9200"
  index: "optimaize_keywords"
  batch_size: 100
  analysis:
    analyzer: "standard"
    max_tokens: 10000

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 1

# LLM Configuration
llm:
  default_model: "llama3"         # Default Ollama model
  ollama_url: "http://localhost:11434"  # Ollama server URL
  temperature: 0.7                # Generation temperature (0.0-1.0)
  max_tokens: 2048               # Maximum tokens to generate
  template: "default.txt"         # Default prompt template
  timeout: 120                   # Generation timeout in seconds
  fallback_enabled: true         # Enable graceful fallback on errors

# Logging Configuration
logging:
  level: "INFO"                 # DEBUG, INFO, WARNING, ERROR
  format: "structured"          # structured, simple
  file_logging: true
  log_directory: "data/logs"
  max_file_size: "10MB"
  backup_count: 5

  # Database Configuration
database:
  path: "data/optimaize.db"
  echo: false
  pool_size: 10
  max_overflow: 20