# -*- coding: utf-8 -*-
"""linear_interpolation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HdNMYZvP3RO9mr7j94Uqz2RpGs2Kb7pr
"""

# By submitting this assignment, I agree to the following:
#   "Aggies do not lie, cheat, or steal, or tolerate those who do."
#   "I have not given or received any unauthorized aid on this assignment."
#
# Names:        Aaditya 
#               Yuriy
#               Areen
#               Joaquin
# Section:      576
# Assignment:   Lab 2.8
# Date:         1 09 2022

from math import * #To import math function library
from sympy import *
import math

x1 = 10
y1 = 2026
x2 = 55
y2 = 23026
rad = 6745
circ = rad *2* (math.pi)
position = (y2-y1)/(x2-x1)
rev_t = circ/position
x = symbols('x')
y = position * (x - x1)+ y1
print("Part 1:")
print("For t = 25 minutes, the position p = ",format(y.subs(x,25), '.1f')," kilometers")
print("Part 2:")
print("For t = 300 minutes, the position p = ", y.subs(x,300%rev_t)," kilometers")